In [13]:
import numpy

R = [[5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4]
]

S =np.array( [[5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4]
])
S=S.T
eR=numpy.dot(R,S) #矩阵点乘操作

print(eR)
# numpy.random.randint(low, high=None, size=None, dtype='l')
# 函数的作用是，返回一个随机整型数，范围从低（包括）到高（不包括），即[low, high)。
# 如果没有写参数high的值，则返回[0,low)的值。
P=numpy.random.randint(low=2, high=5, size=(5, 2)) #随机生成一个 5行 2列的矩阵
Q=numpy.random.randint(low=2, high=5, size=(5, 2)) #随机生成一个 5行 2列的矩阵
print("P = \n", P)
print("Q = \n", Q)
Q=Q.T
print("Q.T = \n", Q)
# 访问 P 和 Q 的元素
print("P[0][0] = ",P[0][0])
print("Q[0][0] = ",Q[0][0])

# 计算 P 的第一列和 Q 的第一行的内积
print("Q[0][0] = ",R[0][0])
print("numpy.dot(P[:, 0], Q[0, :] = ",numpy.dot(P[:, 0], Q[0, :]))


print("P[:, 0] = ",P[:, 0])
print("Q[0, :] = ",Q[0, :])
e = R[0][0]-numpy.dot(P[:, 0], Q[0, :])
print(e)


[[35 21 13  9  7]
 [21 17  9  8  4]
 [13  9 27 21 21]
 [ 9  8 21 17 16]
 [ 7  4 21 16 42]]
P = 
 [[2 3]
 [2 3]
 [2 4]
 [2 3]
 [3 3]]
Q = 
 [[2 2]
 [2 3]
 [4 4]
 [3 4]
 [2 3]]
Q.T = 
 [[2 2 4 3 2]
 [2 3 4 4 3]]
P[0][0] =  2
Q[0][0] =  2
Q[0][0] =  5
numpy.dot(P[:, 0], Q[0, :] =  28
P[:, 0] =  [2 2 2 2 3]
Q[0, :] =  [2 2 4 3 2]
-23


In [8]:
import numpy as np

# 生成一个5*5的随机矩阵
mat = np.array([
    [2, 5, 6, 1, 9],
    [3, 4, 1, 8, 6],
    [9, 1, 1, 5, 3],
    [4, 7, 7, 6, 1],
    [1, 1, 8, 2, 3]
])
# mat = [
#     [2, 5, 6, 1, 9],
#     [3, 4, 1, 8, 6],
#     [9, 1, 1, 5, 3],
#     [4, 7, 7, 6, 1],
#     [1, 1, 8, 2, 3]
# ]
# 在使用NumPy库时，
# 需要将列表转换为NumPy数组，
# 这是因为NumPy数组支持向量化运算和广播，
# 而列表不支持这些功能。因此，
# 使用np.array()函数将列表转换为NumPy数组，可以更方便地进行矩阵运算和其他数学操作。
# 在这个例子中，第一个代码段使用了np.array()函数将列表转换为NumPy数组，
# 而第二个代码段直接使用列表，因此第二个代码段在进行矩阵运算时会报错。
print(mat[0, :])
# 打印矩阵
print("Matrix:")
print(mat)

# 计算第一行和第一列的点乘
result = np.dot(mat[0, :], mat[:, 0])
print("Result:")
print(result)


[2 5 6 1 9]
Matrix:
[[2 5 6 1 9]
 [3 4 1 8 6]
 [9 1 1 5 3]
 [4 7 7 6 1]
 [1 1 8 2 3]]
Result:
86
